### ISSUE TITLE
[BUG] 0.10.21 lazyapi conflicts with space-exploration

### ISSUE THREAD

**Issue by Xetaxheb** [ZwerOxotnik/zk-lib#8]
[factorio-previous.log](https://github.com/ZwerOxotnik/zk-lib/files/8646084/factorio-previous.log)

**Describe the bug**
0.10.21 has a conflict with space-exploration 0.5.114

**Steps to reproduce**
1. Install space-exploration and its dependencies
2. Install 0.10.21 zk-lib multipack
3. Try to launch game

```
 ["space-exploration"] = "0.5.114",
  ["space-exploration-graphics"] = "0.5.15",
  ["space-exploration-graphics-2"] = "0.1.2",
  ["space-exploration-graphics-3"] = "0.1.1",
  ["space-exploration-graphics-4"] = "0.1.1",
  ["space-exploration-graphics-5"] = "0.1.2",
  ["space-exploration-postprocess"] = "0.5.30",
  ["zk-lib"] = "0.10.21"
}
   1.020 Loading mod aai-signal-transmission 0.4.4 (data.lua)
   1.096 Loading mod alien-biomes 0.6.7 (data.lua)
   1.404 Loading mod informatron 0.2.2 (data.lua)
   1.538 Loading mod jetpack 0.3.2 (data.lua)
   1.676 Loading mod robot_attrition 0.5.12 (data.lua)
   1.815 Loading mod shield-projector 0.1.3 (data.lua)
   1.948 Loading mod space-exploration 0.5.114 (data.lua)
   1.957 Script @__space-exploration__/collision-mask-util-extended/data/collision-mask-util-extended.lua:121: Named collision layer [flying-layer] set to layer [layer-13]
   1.958 Script @__space-exploration__/collision-mask-util-extended/data/collision-mask-util-extended.lua:121: Named collision layer [projectile-layer] set to layer [layer-14]
   1.959 Script @__space-exploration__/collision-mask-util-extended/data/collision-mask-util-extended.lua:121: Named collision layer [vehicle-layer] set to layer [layer-15]
   1.961 Script @__space-exploration__/collision-mask-util-extended/data/collision-mask-util-extended.lua:121: Named collision layer [empty-space-tile] set to layer [layer-16]
   1.962 Script @__space-exploration__/collision-mask-util-extended/data/collision-mask-util-extended.lua:121: Named collision layer [space-tile] set to layer [layer-17]
   1.963 Script @__space-exploration__/collision-mask-util-extended/data/collision-mask-util-extended.lua:121: Named collision layer [moving-tile] set to layer [layer-18]
   1.964 Script @__space-exploration__/collision-mask-util-extended/data/collision-mask-util-extended.lua:121: Named collision layer [composite-entity-circuit-connection-layer] set to layer [layer-19]
   1.996 Error ModManager.cpp:1588: Failed to load mod "space-exploration": __zk-lib__/experimental/lazyAPI.lua:516: attempt to index local 'prototype' (a boolean value)
stack traceback:
	__zk-lib__/experimental/lazyAPI.lua:516: in function 'extend'
	...ation__/prototypes/phase-1/recipe/rocket-landing-pad.lua:4: in main chunk
	[C]: in function 'require'
	__space-exploration__/data.lua:265: in main chunk
   1.998 Loading mod core 0.0.0 (data.lua)
   2.102 Checksum for core: 3123733693
   2.221 Error ModManager.cpp:1588: Error in assignID: recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
```

**Comment by ZwerOxotnik** [comment]
[https://mods.factorio.com/mod/zk-lib/downloads](https://mods.factorio.com/mod/zk-lib/downloads)  
Thank you for the report. It should work fine on v0.10.22 now.
